---
title: "Can linear transportation infrastructure verges constitute a habitat and/or a corridor for vascular plants in temperate ecosystems? A systematic review"
bibliography: references.bib
csl: elsevier-vancouver.csl
format:
  docx: default
---

**Abstract**

***TODO***

Initiales : SV : Sylvie Vanpeene, AV : Anne Villemey, AJ : Arzhvaël Jeusset,
RS : Romain Sordello, MV : Marianne Vargac, EG : Eric Guinard, EM : Eric le
Mitouard, VR : Vanessa Rauel, AC : Aurélie Coulon, YB : Yves Bertheau, LP :
Louise Percevault, VF : Vinciane Fack, PP : Patrick Pacevicius, VA : Vital
Azambourg, YR : Yorick Reyjol 

 
## Background

For the last decades, human activities have resulted in a global continuous
loss of biodiversity [@butchart_global_2010], and transportation was identified
as one of the ten major threats faced by threatened or near-threatened species
[@maxwell_biodiversity_2016]. Linear transportation infrastructures (LTIs) have
led to habitat loss and degradation, fragmentation and barrier effects, light
and noise disturbance, chemical pollution and direct mortality (e.g. road kill,
electrocution) [@bekker_habitat_2003; @biasotto_power_2018; @feranec_european_2016; @richardson_review_2017; @trombulak_review_2000].
In particular, the splitting of natural habitats and ecosystems into smaller and
more isolated patches (i.e. fragmentation) and the associated loss of habitat
have negative effects on biodiversity [@krauss_habitat_2010]. For instance,
LTIs have induced a decrease in wildlife species abundance at local and large
scales [@benitez-lopez_impacts_2010]. And, through barrier effects LTIs can
restrict wildlife movements, disrupt gene flow and metapopulation dynamics, and
lead to the genetic isolation of populations over several generations (*e.g.*
[@zachos_genetic_2007]).

Considered transversally, LTIs thus generate a demonstrated negative
fragmenting effect on biodiversity, but considered longitudinally, LTIs have
the potential to constitute a habitat and/or movement corridors for
biodiversity by their semi-natural verges [@seiler_effects_2003]. Indeed,
inside the LTI boundaries there is generally a transportation lane (road,
railway, pipeline, powerline, river or canal) and verges which are most often
covered with vegetation (road and railway embankments, strips of grass under
power lines or above buried pipelines, or waterway banks, etc.). Studies
assessing the potential of LTI verges as habitat and/or corridor for wildlife
species have provided contrasted results. For instance, it has been shown that
revegetated highway verges could serve as ecological corridors for native
rodents and fragmentation-tolerant bird species in California, United States of
America [@bolger_use_2001]. At the opposite, a meta-analysis revealed that
densities of mammals and birds, but not raptors, declined in infrastructures
verges [@benitez-lopez_impacts_2010]. The potential of LTI verges as habitat
and/or corridor for wildlife species may also vary with verge management
practices, as one practice (e.g. mowing) can be beneficial for some species
(e.g. disturbance-tolerant species) but not for others (e.g. woody species)
 [@forman_roads_1998; @le_viol_plant_2008].

Knowing the role of LTI verges as habitat and/or corridor for biodiversity is
of importance as verges might contribute to ecological networks. In the last
decades, ecological networks of terrestrial and aquatic continuities
(blue-green infrastructures) aiming to decrease fragmentation have received
much attention from scientists and policymakers [@bennett_linkages_2003]. Meta-analyses of corridor
effectiveness showed that, overall, corridors increase movements of plants,
vertebrates and invertebrates between habitat patches, but that corridor
effectiveness varies among taxa [@gilbert-norton_meta-analytic_2010]. Maintaining such a network of ecological
corridors might be beneficial on the long term in the context of climate change
by facilitating species dispersal to newly suitable areas  [@heller_biodiversity_2009]. In France, the
concept of green and blue infrastructures led to the development of a public
policy named “Trame Verte et Bleue” (meaning green and blue ecological network)
launched by the French Ministry of Ecology in 2007. Accordingly, French
administrative regions have identified ecological networks and they conduct
action plans for preserving and restoring these continuities, for biodiversity.
At a smaller spatial scale, i.e. townships, it has also to be considered in
local urban planning.

### Topic identification and stakeholder input

In France, the LTI network is very dense. For instance, the road network is the
longest (over a million kilometres long, ¼ of the European network) and one of
the densest (1.77 km/km²) of the European Union. As a comparison, Spain, which
has an area close to the one of France, has a road density six times lower
(0.32 km/km²). The railway network is also one of the longest in Europe with
more than 30,000 kilometres of railway lines in use. Thus, such a dense LTI
network means a considerable inherent surface of verges and LTI managers might
substantially contribute to ecological networks. Furthermore, in the
literature, the potential for LTI verges to be a habitat and/or a corridor for
biodiversity seems to exist, but a comprehensive understanding of the
conditions where this is true remains, as far as we know, unavailable. Seminal
reviews on this question were previously published [@trombulak_review_2000; @forman_roads_1998; @farhig_effects_2009] but they focused
on roads and do not fulfil the standards of a systematic review [@pullin_guidelines_2006]. This
situation motivated several French LTI managing companies and the French
Ministry of Ecology to request a systematic review on this issue, at the heart
of the green and blue infrastructure public policy. The French LTI managing
companies are gathered in an informal group, named “Club des Infrastructures
Linéaires & Biodiversité” (CILB), aiming at acting for biodiversity
conservation. The motorway, railway, power line, pipeline and waterway French
stakeholder companies who are members of the CILB were specifically interested
in evaluating whether their LTI verges could contribute to green and blue
infrastructures to improve the management of these verges for that purpose. The
systematic review was assumed to be a relevant scientific method to provide a
sound answer to this practical questioning from LTI managers. A call for tender
for a systematic review was thus launched by the French Ministry of Ecology and
the French Agency for Environment and Energy Management (ADEME) through its
research incentive program related to transportation ecology, named
“Infrastructures de Transport Terrestre, Écosystèmes et Paysage” (ITTECOP),
supported by the CILB and the “Fondation pour la Recherche sur la
Biodiversité” (FRB), a French foundation supporting research in biodiversity.
The French National Museum of National History (MNHN) was then chosen for
conducting the project, in collaboration with the Franch National Institute
of Research, Agriculture and Environment (Inrae), the University Pierre and
Marie Curie (UPMC, Paris 6), the French Centre for Studies and Expertise on
Risks, Environment, Mobility, and Urban and Country Planning (Cerema). At the
beginning of the project, the LTI managers funding the study were met to list
the types of verges they own and the management practices they apply on
those, to define the components of the review question.

The protocol of the systematic review was published in 2016 [@jeusset_can_2016]. Because the
question encompasses all biodiversity, a very large number of articles were
collected. The review process was thus split by taxa in three stages. A first
systematic review focusing on insects was published in 2018 [@villemey_can_2018]. A second
systematic review on vertebrates (mammals, birds, amphibians and reptiles;
organisms like fishes that are not living on or using verges but exclusively
live in or use the LTI itself were not considered in this review) was published
in 2020 (ref). Regarding insects, our systematic review revealed that their
abundance was generally not statistically different between LTI verges and away
from LTIs. Insect abundance was even higher on non-highway road verges than
away from roads. Quelques éléments sur les vertébrés. Here, we propose a third
systematic review on flora to complete the two previous ones. 

### Objective of ther review

The general aim of the review was to determine if LTI verges can provide
habitats or dispersal corridor for flora (i.e. all vascular plants except
stricly aquatic plants). This work exclusively focused on the longitudinal
effect of LTI verges without considering the transversal effect of LTIs such as
barrier effects. The review also aims at assessing the effects of managements
practices (e.g., mowing), as well as of the characteristics of the surrounding
landscape, on the potential of LTI verges for vascular plants. 

___Primary question___

The primary question of the review is: can linear transportation infrastructure
verges constitue habitats and/or corridor for vascular plants in temperate
ecosystems?

___Secondary questions___

The approach in this review consisted in splitting the above primary question
into six specific questions detailed in Table 1. This subdivision was used
during study validity assessment and the synthesis of evidence.

We defined LTI verges as the area up to 30 m from roadways, waterways or
railways, or the area (whatever the width) below power lines or below/above
pipelines. We considered the surrounding landscape to be at, at least, 1 km
around the LTI.

___Components of the primary question___

Population: All vascular plant (except strictly aquatic plants) species and
communities.

Exposure: LTI verges; i.e. road, railway, power line and pipeline verges and
waterway banks. Regarding the latter, as our systematic review focused on LTIs,
we only considered navigable waterways (navigable rivers and canals) as
relevant exposures.

Intervention: Management practices (e.g. mowing) or human-induced disturbances
(e.g. waterway channelization) on LTI verges. 

Comparator: Temporal and/or spatial comparators, including but not restricted
to ecosystem present before versus after infrastructure construction (LTI verge
creation), LTI verge before versus after management intervention), LTI verge
versus nearby similar habitats away from LTIs, LTI verge managed with one
practice versus unmanaged LTI verge or LTI verges managed with a different
practice. 

Outcomes: All outcomes relating to species presence or species dispersal,
including but not restricted to species richness, abundance, community
composition and species dispersal. 

Context: Because the funders requested an evidence synthesis applicable to
western Europe, we restricted our synthesis to temperate zones.

**Table 1:** Details of the six specific questions of the review

## Methods

The methods are described in details in an a priori systematic review protocol
(ref). We summarize it here and present the small deviations from this protocol
that we made when conducting the review. The methods follow the Collaboration
for Environmental Evidence (CEE) Guidelines and Standards for Evidence
Synthesis in Environmental Management (ref) unless noted otherwise.

**Table 2:**  Sub-search strings selected and used in Web Of Science Core
Collection and Zoological Records publications databases. The asterisk (\*)
represents any group of characters, including no character. The dollar sign (
\$) represents zero or one character. The quotation marks (“”) allow to look
for an exact phrase. Strategies 1 and 2 are explained in Additional file X.

___Search for articles___

_Search strings_

The review team identifed English search terms to be combined in search
strings. For all keywords listed wild-cards may be used to allow the use of
derivations of the word’s root and to account for the possibility of finding a
word in various spellings (English from Great Britain or from the United
States) and with various endings (singular or plural). 

We tested a first search string combining some of the search terms with Boolean
operators of Web Of Science Core Collection (with search on “Topic”). To assess
the comprehensiveness of the search string, we compared the search hits to the
articles of the test list indexed in the database (see Additional file X for
the list of articles of the test list and how it was constituted). Then, we
modifed the search string by removing some of the search terms and including
new ones, to increase the number of articles of the test list retrieved [@jeusset_can_2016].
At last, the search string that produced the highest efficiency (i.e. total
number of search hits as low as possible with the highest number of articles
from the test list retrieved) was a set of four sub-search strings displayed in
Table 2. 

_Publication databases_

We first listed the databases to which the members of our review team had
access. The database selection was then based on three criteria [@jeusset_can_2016]:

* Topic: the database(s) had to cover ecology; 
* Accessibility/reproducibility/sustainability: the database(s) had to be accessible by the whole review team, and by researchers all over the world (as a guarantee of reproducibility and further reviewing); 
* Comprehensiveness: number of articles indexed in the database(s) among the articles of the test list (Additional file 2)

These criteria led us to select two databases: Web Of Science Core Collection
(with subscriptions: Science Citation Index Expanded 1956-present, Social
Sciences Citation Index 1975-present, Arts and Humanities Citation Index
1975-present, Conference Proceedings Citation Index-Science 1990-present,
Conference Proceedings Citation Index-Social Science & Humanities 1990-present,
Book Citation Index-Science 2005-present, Book Citation Index-Social Sciences
and Humanities 2005-present, Emerging Sources Citation Index 2015-present,
Current Chemical Reactions 1985-present, and Index Chemicus 1993-present; XX
articles indexed out of the XXX articles of the test list) and Zoological
Records (subscribed timespan 1864-present, XX articles out of the XXX
articles). Searches on these two databases were made on “Topic”.

_Search engines_

 We performed additional searches using three search engines: 
* Google Scholar (https://scholar.google.fr/); 
* BASE (Bielefeld Academic Search Engine, https:// www.base-search.net/); 
* CORE (https://core.ac.uk/). Because these search engines could only handle a limited number of search terms and did not allow the use of all wildcards, the search strings used for publication databases were simplified. We thus developed a search string for each of the five LTIs (Additional file 3). In Google Scholar, results were sorted by relevance, with the boxes “include patents” and “include citations” unchecked. In BASE, results were sorted by relevance, with the box “boost open access documents” unchecked and the box “Verbatim search” checked. For each of the five search strings, we retrieved the first 20 hits.

_Specialist websites_

We searched for links or references to relevant articles and data on 11
specialist websites including a journal special issue on transportation ecology
(Additional file 4).

_Supplementary searches_

To retrieve grey literature, we contacted by email national and international
experts of transportation ecology, through the Ecodif (now SFEcodif),
Transenviro, Wftlistserv and IENE mailing lists and by posting a call on social
media (https://fr.linkedin.com/). SFEcodif is a French mailing list about
ecology and evolution which counted around 7000 subscribers (https://www.sfeco
logie.org/sfecodif/), and Transenviro, Wftlistserv and IENE mailing lists are
international mailing lists about transportation ecology. Together, the
Transenviro and Wftlistserv mailing lists (http://www.itre.ncsu.edu/CTE/
Lists/index.asp) gathered about 600 contacts and the IENE mailing list
(http://www.iene.info/) counted around 300 contacts. All these mailing lists
were accessed on 22 September 2015. Eventually, we contacted nearly two
thousand people (N=1902) by individual email. Organizations funding the
systematic review also provided us with their unpublished reports. As well,
some experts spontaneously sent us documents on flora after having heard about
our project (see below).

_Dates of literature searches_

Literature searches were performed in three stages. First, we performed
searches in Web Of Science Core Collection publication database, in Zoological
Records publication database, and in Google Scholar search engine on April 27th
2015, February 1st 2016, and March 4th to 9th 2016, respectively. The call for
grey literature was performed on April 21st 2015. All articles published in
2016 were not considered during these first searches.

Second, searches were updated on June 15th 2018 for Web Of Science Core
Collection and Zoological Records publication databases, and on November 6th
2018 for Google Scholar, to retrieve articles published from 2016 onward until
these dates (Additional file 4). New searches on specialist websites were
conducted from November 26th 2018 to December 4th 2018, and searches on BASE
and CORE search engines were updated on November 7th and 8th 2018,
respectively.

Third, we performed an update from articles published between 2018 and 2020 on
March 3rd, 2021 for Web Of Science Core Collection (N=6193 articles) and
Zoological Records publication databases (N=1240 articles). Due to time
restriction, no update was conducted however for the other sources of
literature (Google Scholar, CORE, BASE). There was no update of the call for
grey literature either, but we received spontaneously documents from experts by
emails: on 20th October 2021 from Mayenne Nature Environnement (N=10 articles)
and on the 15 November 2021 from Frédéric Hendoux, director of the Conservation
Botanique National du Bassin Parisien (N=4 articles).

Finally, articles from a previsouly published review on roadside management
were included into our review (Jakobsson 2018).

### Article screening and study eligibility criteria

_Screening process_

The articles collected from online publication databases were screened by
several member of the review team for eligibility (according to the criteria
described in the next section) through three successive stages : first on
titles (performed by SV, AV, AJ, RS, MV, EG, EM, VR, LP), second on abstracts
(performed by SV, AV, AJ, RS, MV, EG, EM, VR, AC, YB, LP), and third on
full-texts (performed by LP, VF, VR, SV, AV, AJ, AC, DYO, EG, EM, MV, RS, PP,
VA, YB, YR). The number of articles screened by each member of the review team
is detailed in the supplementary file X.

The screening is conservative at each stage : in cases of doubt, articles
proceed to the next stage for further assessment. The agreement between
screener was assessed before beginning a screening stage (title, abstract or
full-text screening stage) by computing a Randolph’s Kappa coefficient [ref] on
a number of references randomly sampled among the database of articles about
flora. These randomly sampled articles were screened by each of the reviewers
independently of each other.
The agreement between screeners was assessed before beginning the screening on
titles, abstracts and full-text by computing a Randolph’s Kappa coefficient
[ref] on a number of references randomly sampled among the sets of articles and
screened by each of the reviewers independently of each other. We considered
200, 20 and 50  randomly sampled references to be sufficient to assess the
agreement between screeners during title, abstract and full-text screening,
respectively. It is a relatively small proportion of the total number of
references to be screened, but these numbers were based on our experience with
the previous systematic reviews published on insects and then on vertebrates
[ref, ref]. A minimal coefficient of 0.6 was considered an acceptable level of
agreement between reviewers. All disagreements were discussed by reviewers, so
that diferences in screeners’ understanding of eligibility criteria could be
resolved. When the coefficient was lower than 0.6 the operation was repeated
until reaching a coefficient larger than 0.6.

_Eligibility criteria_

At each stage of screening, article eligibility was based on a list of
selection criteria. At the stage of title screening, these criteria mainly
encompassed both the subject (ecology and related disciplines) and the
population and exposure/intervention of the article (Table  3). The same
criteria were applied at the stage of abstract screening, to which we added
criteria regarding the exposure/intervention, the comparator, the outcomes or
the study type (Table  4). Articles without abstract were discarded due to
their high number and time constraints, and as this protocol was followed for
the previous two reviews of our project. Finally, the same criteria as for the
abstract stage were used for the stage of full-text screening, to which we
added new inclusion criteria regarding the language, the climate, the type of
publication or the specifc questions covered (Table 5). We considered that a
study was not relevant to the purpose of the review, and thus discarded it, if
the comparator was inappropriate (comparison between diferent seasons,
comparator difcult to interpret for the purposes of this review, high contrast
of habitat with the comparator (e.g. herbaceous vegetation compared to forest),
etc.], if the sampling was not strictly done on verges (we defined LTI verges
as the area up to 30 m from roadways, waterways, or railways, or the area
(whatever the width) below power lines or below/above pipelines), or if—for
questions Q5 and Q6—the landscape scale was below 1 km. As our review focused
on transportation infrastructures, we also made sure at full-text screening
stage that only paved roads and navigable rivers and canals were included. This
information is unfortunately rarely provided for waterways, so we included all
articles with Strahler [@strahler_quantitative_1957] stream order above three, canals and rivers, and we
excluded all articles with stream order equal or below three and articles with
no information on stream order.

**Table 3:** List of inclusion/exclusion criteria at the stage of title screening

**Table 4: List of inclusion criteria at the stage of abstract screening**

<!--
* 1. Butchart SHM, Walpole M, Collen B, Strien A van, Scharlemann JPW, Almond REA, et al. Global Biodiversity: Indicators of Recent Declines. Science. 2010;328:1164‑8. 
* 2. Maxwell SL, Fuller RA, Brooks TM, Watson JEM. Biodiversity: The ravages of guns, nets and bulldozers. Nature News. 2016;536:143. 
* 3. Bekker H, Iuell B. Habitat fragmentation due to infrastructure. Making Connections. 2003;15. 
* 4. Biasotto LD, Kindel A. Power lines and impacts on biodiversity: A systematic review. Environmental Impact Assessment Review. 2018;71:110‑9. 
* 5. Dorsey B, Olsson M, Rew LJ. Ecological Effects of Railways on Wildlife. Handbook of Road Ecology [Internet]. John Wiley & Sons, Ltd; 2015 [cité 21 oct 2019]. p. 219‑27. Disponible sur: https://onlinelibrary.wiley.com/doi/abs/10.1002/9781118568170.ch26
* 6. Jaeger JAG, Soukup T, Schwick C, Madriñan LF, Kienast F. Lanscape fragmentation in Europe. European Landscape Dynamics Corine land cover data. Jan Feranec, Tomas Soukup, Gerard Hazeu, and Gabriel Jaffrain. Boca Raton, USA: CRC Press; 2016. 
* 7. Richardson ML, Wilson BA, Aiuto DA, Crosby JE, Alonso A, Dallmeier F, et al. A review of the impact of pipelines and power lines on biodiversity and strategies for mitigation. Biodiversity and Conservation. 2017;26:1801–1815. 
* 8. Trombulak SC, Frissell CA. Review of Ecological Effects of Roads on Terrestrial and Aquatic Communities. Conservation Biology. 2000;14:18‑30. 
* 9. Krauss J, Bommarco R, Guardiola M, Heikkinen RK, Helm A, Kuussaari M, et al. Habitat fragmentation causes immediate and time-delayed biodiversity loss at different trophic levels. Ecology Letters. 2010;13:597‑605. 
* 10. Benitez-Lopez A, Alkemade R, Verweij PA. The impacts of roads and other infrastructure on mammal and bird populations: A meta-analysis. Biological Conservation. 2010; 
* 11. Zachos FE, Althoff C, Steynitz Y v., Eckert I, Hartl GB. Genetic analysis of an isolated red deer (Cervus elaphus) population showing signs of inbreeding depression. Eur J Wildl Res. 2007;53:61‑7. 
* 12. Seiler A. Effects of infrastructure on nature. COST Action 341 - Habitat Fragmentation due to Transportation Infrastructure: The European review. Trocmé, M.; Cahill, S.; De Vries, J.G.; Farrall, H.; Folkeson, L.; Fry, G.; Hicks, C. and Peymen, J. Luxembourg: Office for Official Publications of the  European Communities; 2002. p. 31‑50. 
* 13. Bolger DT, Scott TA, Rotenberry JT. Use of corridor-like landscape structures by bird and small mammal species. Biological Conservation. 2001; 
* 14. Forman RTT, Alexander LE. Roads and their major ecological effects. Annu Rev Ecol Syst. 1998;29:207‑31. 
* 15. Le Viol I, Julliard R, Kerbiriou C, de Redon L, Carnino N, Machon N, et al. Plant and spider communities benefit differently from the presence of planted hedgerows in highway verges. Biological Conservation. 2008; 
* 16. Bennett AF. Linkages in the Landscape: The Role of Corridors and Connectivity in Wildlife Conservation. IUCN. Gland, Switzerland and Cambridge, UK; 2003. 
* 17. Gilbert‐Norton L, Wilson R, Stevens JR, Beard KH. A Meta-Analytic Review of Corridor Effectiveness. Conservation Biology. 2010;24:660‑8. 
* 18. Heller NE, Zavaleta ES. Biodiversity management in the face of climate change: A review of 22 years of recommendations. Biological Conservation. 2009;142:14‑32. 
* 19. Fahrig L, Rytwinski T. Effects of roads on animal abundance: An empirical review and synthesis. Ecology and Society [Internet]. 2009 [cité 14 oct 2019];14. Disponible sur: https://ir.library.carleton.ca/pub/4484
* 20. Pullin AS, Stewart GB. Guidelines for Systematic Review in Conservation and Environmental Management. Conservation Biology. 2006;20:1647‑56. 
* 21. Jeusset A, Vargac M, Bertheau Y, Coulon A, Deniaud N, Flamerie De Lachapelle F, et al. Can linear transportation infrastructure verges constitute a habitat and/or a corridor for biodiversity in temperate landscapes? A systematic review protocol. Environmental Evidence. 2016;5:5. 
* 22. Villemey A, Jeusset A, Vargac M, Bertheau Y, Coulon A, Touroult J, et al. Can linear transportation infrastructure verges constitute a habitat and/or a corridor for insects in temperate landscapes? A systematic review. Environmental Evidence. 2018;7:5. 
* 26. Strahler AN. Quantitative Analysis of Watershed Geomorphology. Transactions American Geophysical Union. 1957;38:913‑20. 
* 27. Lajeunesse MJ. Recovering missing or partial data from studies: a survey of conversions and imputations for meta-analysis. Handbook of meta-analysis in ecology and evolution. Princeton University Press. Princeton, New Jersey: Koricheva, J. and Gurevitch, J. and Mengersen, K.; 2013. p. 195‑206. 
* 28. Higgins JPT, White IR, Anzures‐Cabrera J. Meta-analysis of skewed data: Combining results reported on log-transformed or raw scales. Statistics in Medicine. 2008;27:6072‑92. 
-->

## References

::: {#refs}
:::

